apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-qdrant-api-key
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
{{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-qdrant-api-key" .Release.Name) }}
{{- if $existing }}
  api-key: {{ index $existing.data "api-key" }}
{{- else }}
  api-key: {{ randAlphaNum 32 | b64enc }}
{{- end }}
