{{- if gt (.Values.hpa.minReplicas | int) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-api
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
{{- end }}
