apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
{{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-redis" .Release.Name) }}
{{- if $existing }}
  password: {{ index $existing.data "password" }}
{{- else }}
  password: {{ randAlphaNum 32 | b64enc }}
{{- end }}
