version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/Iverson.AdminUI"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/Iverson.Clients/TypeScript"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/Iverson.Clients/Go"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/Iverson.Clients/Java"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/Iverson.Clients/Python"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/Iverson.Agents/Python"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
