apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-authentik-blueprints
data:
{{- range $path, $bytes := .Files.Glob "blueprints/*.yaml" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
