apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-authentik
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://{{ .Values.global.ingressHost }}"
    nginx.ingress.kubernetes.io/cors-allow-methods: "POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "content-type"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
{{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts: [{{ printf "authentik.%s" .Values.global.ingressHost | quote }}]
      secretName: {{ .Values.ingress.tlsSecretName | quote }}
{{- end }}
  rules:
    - host: {{ printf "authentik.%s" .Values.global.ingressHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-authentik
                port:
                  number: 9000
