apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-authentik-app
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
{{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-authentik-app" .Release.Name) }}
{{- if $existing }}
  secret-key: {{ index $existing.data "secret-key" }}
  bootstrap-password: {{ index $existing.data "bootstrap-password" }}
  bootstrap-token: {{ index $existing.data "bootstrap-token" }}
{{- else }}
  secret-key: {{ randAlphaNum 50 | b64enc }}
  bootstrap-password: {{ randAlphaNum 32 | b64enc }}
  bootstrap-token: {{ randAlphaNum 60 | b64enc }}
{{- end }}
