apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-authentik-loadtest-client
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
{{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-authentik-loadtest-client" .Release.Name) }}
{{- if $existing }}
  client-id: {{ index $existing.data "client-id" }}
  client-secret: {{ index $existing.data "client-secret" }}
{{- else }}
  client-id: {{ randAlphaNum 40 | b64enc }}
  client-secret: {{ randAlphaNum 50 | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-authentik-webtest-client
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
{{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-authentik-webtest-client" .Release.Name) }}
{{- if $existing }}
  client-id: {{ index $existing.data "client-id" }}
  client-secret: {{ index $existing.data "client-secret" }}
{{- else }}
  client-id: {{ randAlphaNum 40 | b64enc }}
  client-secret: {{ randAlphaNum 50 | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-authentik-admin-automation-client
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
{{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-authentik-admin-automation-client" .Release.Name) }}
{{- if $existing }}
  client-id: {{ index $existing.data "client-id" }}
  client-secret: {{ index $existing.data "client-secret" }}
{{- else }}
  client-id: {{ randAlphaNum 40 | b64enc }}
  client-secret: {{ randAlphaNum 50 | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-authentik-human-oidc-client
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
{{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-authentik-human-oidc-client" .Release.Name) }}
{{- if $existing }}
  client-id: {{ index $existing.data "client-id" }}
{{- else }}
  client-id: {{ randAlphaNum 40 | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-authentik-loadtest-human-client
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
{{- $existingHuman := lookup "v1" "Secret" .Release.Namespace (printf "%s-authentik-loadtest-human-client" .Release.Name) }}
{{- if $existingHuman }}
  client-id: {{ index $existingHuman.data "client-id" }}
{{- else }}
  client-id: {{ randAlphaNum 40 | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-authentik-smoke-test-user
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
{{- $existingSmokeUser := lookup "v1" "Secret" .Release.Namespace (printf "%s-authentik-smoke-test-user" .Release.Name) }}
{{- if $existingSmokeUser }}
  password: {{ index $existingSmokeUser.data "password" }}
{{- else }}
  password: {{ randAlphaNum 32 | b64enc }}
{{- end }}
