apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-authentik-postgres
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/basic-auth
data:
{{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-authentik-postgres" .Release.Name) }}
{{- if $existing }}
  username: {{ index $existing.data "username" }}
  password: {{ index $existing.data "password" }}
{{- else }}
  username: {{ "authentik" | b64enc }}
  password: {{ randAlphaNum 32 | b64enc }}
{{- end }}
