replicas: 2
storageSize: 500Gi
storageClassName: ""
imageTag: "v1.12.0"
resources:
  requests: { cpu: "8", memory: "64Gi", ephemeral-storage: "2Gi" }
  limits: { cpu: "8", memory: "64Gi", ephemeral-storage: "4Gi" }
nodeSelector: {}
tolerations: []
