{{- if gt (.Values.fe.replicas | int) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-starrocks-fe
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.starrocks.ownerreference/name: {{ .Release.Name }}-starrocks-fe
      app.kubernetes.io/component: fe
{{- end }}
