apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-starrocks-app
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
{{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-starrocks-app" .Release.Name) }}
{{- if $existing }}
  root-password: {{ index $existing.data "root-password" }}
  app-password: {{ index $existing.data "app-password" }}
{{- else }}
  root-password: {{ randAlphaNum 32 | b64enc }}
  app-password: {{ randAlphaNum 32 | b64enc }}
{{- end }}
