{{- if gt (.Values.replicas | int) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-ollama
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ollama
{{- end }}
