apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-ollama-data
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.storageSize }}
